development:
  adapter: mysql2
  database: dd_dev
  username: <%= ENV["DB_USER"]%>
  password: <%= ENV["DB_PASS"]%>
  host: localhost

test:
  adapter: mysql2
  database: dd_test
  username: <%= ENV["DB_USER"]%>
  password: <%= ENV["DB_PASS"]%>
  host: localhost

